version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: consoleshop-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: consoleshop
      POSTGRES_USER: consoleshop_user
      POSTGRES_PASSWORD: consoleshop_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: